apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuhgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yuhgmt
  template:
    metadata:
      labels:
        app: yuhgmt
    spec:
      containers:
      - image: okteto.dev/yuhgmt:latest
        name: yuhgmt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "357ea7e5-2672-4ab9-8771-a82b90ad27d1"
        - name: Vless_Path
          value: "/357ea7e5-2672-4ab9-8771-a82b90ad27d1-vless"
        - name: Vmess_UUID
          value: "357ea7e5-2672-4ab9-8771-a82b90ad27d1"
        - name: Vmess_Path
          value: "/357ea7e5-2672-4ab9-8771-a82b90ad27d1-vmess"
        - name: Share_Path
          value: "/v2link"
